### ISSUE TITLE
[FLIN-60] Add table for users to relational database

### ISSUE THREAD

**Issue by MarcosPetrucci** [FlinkFood/FlinkFood#10]
## User Story

**As a user, I would want a source of all the registered users on the platform, So that I could keep track of number of users**

### Acceptance Criteria

- [x] Has a mock database SQL file with necessary tables

### Tasks

- [x] Create a mock database SQL

### Definition of Done

- [x] All acceptance criteria are met.
- [x] Code is documented.
- [x] Unit tests are written (if applicable).
- [x] Peer-reviewed.

---

**Additional Information:**
This task will be done together with FLIN-81
