### ISSUE TITLE
[FLIN-80] Add Java to docker container

### ISSUE THREAD

**Issue by MarcosPetrucci** [FlinkFood/FlinkFood#12]
## User Story

**"As a user, I would want my app to be containarized, So that it would be easier to maintain"**

### Acceptance Criteria

- [ ] Java container image
- [ ] Running across architectures
- [ ] Have proper documentation

### Tasks

- [ ] Crete Java container image
- [ ] Test the Java container image
- [ ] Test the image across architectures
- [ ] Do the documentation

### Definition of Done

- [ ] All acceptance criteria are met.
- [ ] Code is documented.
- [ ] Unit tests are written (if applicable).
- [ ] Peer-reviewed.

---

**Additional Information:**
We will try to do a script to run simple programs automatically
