### ISSUE TITLE
[FLIN-103] Orchestration of all docker images

### ISSUE THREAD

**Issue by VegSja** [FlinkFood/FlinkFood#14]
## User Story

As a user, I would want my app to be containarized, So that it would be easier to maintain

### Acceptance Criteria

1. Running docker compose up creates every needed docker container to run and test our application

### Tasks

- [x] Java container present
- [x] Kafka
- [x] Debezium
- [x] Flink
- [x] MongoDB
- [x] PostgreSQL 

### Definition of Done

- [x] All acceptance criteria are met.
- [x] Code is documented.
- [x] Unit tests are written (if applicable).
- [x] Peer-reviewed.
