### ISSUE TITLE
[FLIN-86] Use Apache Flink to make first letter of username column uppercase

### ISSUE THREAD

**Issue by lucamozzz** [FlinkFood/FlinkFood#16]
## User Story

As a user, I would want to alter user data making the first letter of the username uppercase, So that I can fix data corruption in my table

### Acceptance Criteria
The Flink job performs the correct data manipulation and is able to read/write data from/to the source/sink.

### Tasks

- [x] Connect to a Kafka topic
- [x] Manipulate data
- [x] Store data in MongoDB

### Definition of Done

- [ ] All acceptance criteria are met.
- [x] Code is documented.
- [x] Unit tests are written (if applicable).
- [x] Peer-reviewed.

**Comment by MarcosPetrucci** [comment]
Approved by customer
