### ISSUE TITLE
[FLIN-75] Create script to populate user table with mockdata with postgresSQL

### ISSUE THREAD

**Issue by AZANK7173** [FlinkFood/FlinkFood#19]
## User Story

**As a user, I would want a source of all the registered users on the platform, So that I could keep track of number of users**

### Acceptance Criteria

1. [ ] Database populated with some data

### Tasks

- [ ] Create locally algorithm to generate some random data
- [ ] Modify the sql file to be inserted automatically

### Definition of Done

- [ ] All acceptance criteria are met.
- [ ] Code is documented.
- [ ] Unit tests are written (if applicable).
- [ ] Peer-reviewed.

---

**Additional Information:**
For the next sprint I'll use some better random data generation instead of doing locally with tools online and add it on the code
