### ISSUE TITLE
[FLIN-79] Setup docker with Flink, Kafka, Debezium

### ISSUE THREAD

**Issue by VegSja** [FlinkFood/FlinkFood#5]
## User Story

As a user, I would want my app to be containarized, So that it would be easier to maintain

### Acceptance Criteria

1. Contains docker image for Apache Flink
2. Contains docker image for Apache Kafka
3. Contains docker image for Debezium

### Tasks

- [x] Contains docker image for Apache Flink
- [x] Contains docker image for Apache Kafka
- [x] Contains docker image for Debezium

### Definition of Done

- [x] All acceptance criteria are met.
- [x] Code is documented.
- [x] Unit tests are written (if applicable).
- [x] Peer-reviewed.

---

**Additional Information:**
This is for just creating the docker images. Orchestration will be done later

**Comment by MarcosPetrucci** [comment]
@VegSja Just to clarify, this would also apply to my task "Add relational data base container"

Can I edit the issue adding my requirements as well? I think I should follow the same _Definition of Done_ criteria
