### ISSUE TITLE
[FLIN-81] Add relational database to container

### ISSUE THREAD

**Issue by MarcosPetrucci** [FlinkFood/FlinkFood#9]
## User Story

**As a user, I would want my app to be containarized, So that it would be easier to maintain**

### Acceptance Criteria

- [x] Contains docker image of relational database
- [x] Contains SQL code of a mock database

### Tasks

- [x] Create SQL code of a mock database
- [x] Implement a relational database container 

### Definition of Done

- [x] All acceptance criteria are met.
- [x] Code is documented.
- [x] Peer-reviewed.

---

**Additional Information:**

- Added the database schema
- I would appreciate to add a shell script to automatically run the SQL

**Comment by PolimiGiovanniArriciati** [comment]
No Marcos! Is not working *automagically*!!
